apiVersion: v1
kind: Service
metadata:
  name: lib-web-service
spec:
  type: NodePort
  selector:
    app: lib-web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080  # Exposes the service on this port
