apiVersion: v1
kind: Service
metadata:
  name: lib-db-cluster-svc
  namespace: library-site
spec:
  selector:
    app: lib-db
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
