apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lib-db-pvc
  namespace: library-site
  labels:
    app: lib-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
