apiVersion: v1
kind: PersistentVolume
metadata:
  name: lib-db-pv
  namespace: library-site
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/lib-web-db"
