apiVersion: v1
kind: Secret
metadata:
  name: lib-db-secret
  namespace: library-site
type: Opaque
data:
  username: bGliX2JhY2tfYWRtaW4=  # base64 encoded value of 'lib_back_admin'
  password: bGliX2JhY2tfcGFzcw==  # base64 encoded value of 'lib_back_pass'
